@baseUrl = http://localhost:3333

##
# @name lista_vagas
GET {{baseUrl}}/vagas
Content-Type: application/json

###
# @name lista_estados
GET {{baseUrl}}/estados
Content-Type: application/json

###
# @name lista_deficiencia
GET {{baseUrl}}/deficiencia
Content-Type: application/json

