export type ViewCandidatoModel = {
    id: string,
    sobreMim: string,
    empresasExcluidas: string,
    vagaExclusivaPCD: string,
    cargoRecenteAtual: string,
    cargoDesejado: string,
    experiencia: string,
    estadoSelecionadoId: string,
    pcd: string,
    clt: string,
    pj: string,
    btc: string,
    remoto: string,
    hibrido: string,
    presencial: string,
    pagamentopj: string,
    pagamentoclt: string,
    pagamentobtc: string,
    pretensaoPJ: string,
    pretensaoCLT: string,
}

